/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 18 avr. 2011, 01:44:34
 */
package examples.modem;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author nabster
 */
public class NewJFrame extends javax.swing.JFrame
{

    /** Creates new form NewJFrame */
    public NewJFrame()
    {
        initComponents();
        getContentPane().add(new JLabel("Hello"));
        getContentPane().add(new JLabel("Good"));
         getContentPane().add(new JPanel(), "dock west");
        getContentPane().add(new JButton("Hello"), "span 2");
        getContentPane().add(new JButton("World"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new net.miginfocom.swing.MigLayout());

        jToggleButton1.setText("jToggleButton1");
        getContentPane().add(jToggleButton1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
